version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb  # Ensures MongoDB starts before the backend
    networks:
      - demo
    environment:
      MONGO_URI: mongodb://mongo:27017/todo  # MongoDB connection string

  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - demo

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB port to the host (optional, for local development)
    networks:
      - demo
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data across container restarts

networks:
  demo:
    driver: bridge  # Use the bridge network driver for communication between services

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data on the host filesystem
